# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua: [lua5.1, lua5.2, lua5.3, luajit]
     

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install packages
        run: sudo apt-get install ${{ matrix.lua }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run Tests
        run: |
          echo Running tests for ${{ matrix.lua }}
          cd $GITHUB_WORKSPACE
          ${{ matrix.lua }} test.lua
