# This is a basic workflow to help you get started with Actions

name: Unit Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lua: [lua5.1, lua5.2, lua5.3, lua5.4, luajit]
     

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install packages
        run: sudo apt-get install ${{ matrix.lua }}
        if: ${{ matrix.lua != 'lua5.4' }}

      - name: Build Lua
        if: ${{ matrix.lua == 'lua5.4' }}
        run: |
          wget https://www.lua.org/ftp/lua-5.4.1.tar.gz
          tar -xvzf lua-5.4.1.tar.gz
          cd lua-5.4.1
          make linux
          sudo make install
          sudo ln -s /usr/local/bin/lua /usr/local/bin/lua5.4
          cd ..
          rm -r lua-5.4.1 lua-5.4.1.tar.gz

      - name: Install luarocks
        run: sudo apt-get install luarocks && sudo luarocks install bit32
        if: ${{ matrix.lua == 'lua5.1' }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run Unit Tests
        run: |
          echo Running tests for ${{ matrix.lua }}
          ${{ matrix.lua }} -v
          cd $GITHUB_WORKSPACE
          ${{ matrix.lua }} test.lua

      - name: Run Unit Tests (JIT)
        run: |
          echo Running tests with jit for ${{ matrix.lua }}
          ${{ matrix.lua }} -v
          cd $GITHUB_WORKSPACE
          ${{ matrix.lua }} test.lua -j

      - name: Package
        run: mkdir dist && ${{ matrix.lua }} pack.lua dist/ucl.lua
        if: ${{ matrix.lua == 'luajit' }}

      - uses: actions/upload-artifact@v2
        if: ${{ matrix.lua == 'luajit' }}
        with:
          name: ucl
          path: dist
